// pkg/mapping/wappalyzer.go - 统一定义
package mapping

// WappalyzerNucleiMapping Wappalyzer技术到Nuclei标签的内置映射
// 参考 nuclei 源码: https://github.com/projectdiscovery/nuclei/blob/main/pkg/protocols/common/automaticscan/automaticscan.go
var WappalyzerNucleiMapping = map[string][]string{
	// Web服务器
	"nginx":              {"nginx"},
	"apache":             {"apache"},
	"apache http server": {"apache"},
	"microsoft iis":      {"iis"},
	"iis":                {"iis"},
	"lighttpd":           {"lighttpd"},
	"tomcat":             {"tomcat"},
	"apache tomcat":      {"tomcat"},
	"jetty":              {"jetty"},
	"caddy":              {"caddy"},
	"openresty":          {"nginx", "openresty"},

	// CMS
	"wordpress":   {"wordpress", "wp"},
	"joomla":      {"joomla"},
	"drupal":      {"drupal"},
	"magento":     {"magento"},
	"shopify":     {"shopify"},
	"woocommerce": {"woocommerce", "wordpress"},
	"prestashop":  {"prestashop"},
	"opencart":    {"opencart"},
	"typo3":       {"typo3"},
	"concrete5":   {"concrete5"},
	"ghost":       {"ghost"},
	"hugo":        {"hugo"},
	"hexo":        {"hexo"},
	"jekyll":      {"jekyll"},
	"mediawiki":   {"mediawiki"},
	"xwiki":       {"xwiki"},
	"confluence":  {"confluence", "atlassian"},
	"sharepoint":  {"sharepoint", "microsoft"},

	// 框架
	"spring":           {"spring"},
	"spring boot":      {"springboot", "spring"},
	"spring framework": {"spring"},
	"struts":           {"struts", "apache-struts"},
	"apache struts":    {"struts", "apache-struts"},
	"django":           {"django"},
	"flask":            {"flask"},
	"fastapi":          {"fastapi"},
	"laravel":          {"laravel"},
	"symfony":          {"symfony"},
	"codeigniter":      {"codeigniter"},
	"yii":              {"yii"},
	"cakephp":          {"cakephp"},
	"rails":            {"rails", "ruby-on-rails"},
	"ruby on rails":    {"rails", "ruby-on-rails"},
	"express":          {"express", "nodejs"},
	"express.js":       {"express", "nodejs"},
	"next.js":          {"nextjs", "nodejs"},
	"nuxt.js":          {"nuxtjs", "nodejs"},
	"nest.js":          {"nestjs", "nodejs"},
	"koa":              {"koa", "nodejs"},
	"fastify":          {"fastify", "nodejs"},
	"gin":              {"gin", "golang"},
	"echo":             {"echo", "golang"},
	"beego":            {"beego", "golang"},
	"asp.net":          {"asp.net", "microsoft"},
	"asp.net mvc":      {"asp.net", "microsoft"},
	".net":             {"asp.net", "microsoft"},
	"thinkphp":         {"thinkphp"},
	"yii framework":    {"yii"},

	// 前端框架
	"react":       {"react"},
	"vue.js":      {"vuejs"},
	"vue":         {"vuejs"},
	"angular":     {"angular"},
	"angularjs":   {"angular"},
	"jquery":      {"jquery"},
	"bootstrap":   {"bootstrap"},
	"backbone.js": {"backbone"},
	"ember.js":    {"ember"},

	// 应用服务器
	"weblogic":        {"weblogic", "oracle"},
	"oracle weblogic": {"weblogic", "oracle"},
	"websphere":       {"websphere", "ibm"},
	"ibm websphere":   {"websphere", "ibm"},
	"jboss":           {"jboss"},
	"wildfly":         {"wildfly", "jboss"},
	"glassfish":       {"glassfish"},
	"resin":           {"resin"},
	"coldfusion":      {"coldfusion", "adobe"},
	"adobe coldfusion": {"coldfusion", "adobe"},

	// 数据库
	"mysql":                {"mysql"},
	"postgresql":           {"postgresql"},
	"mongodb":              {"mongodb"},
	"redis":                {"redis"},
	"elasticsearch":        {"elasticsearch", "elastic"},
	"memcached":            {"memcached"},
	"couchdb":              {"couchdb"},
	"cassandra":            {"cassandra"},
	"oracle":               {"oracle"},
	"microsoft sql server": {"mssql", "microsoft"},
	"mssql":                {"mssql", "microsoft"},
	"mariadb":              {"mariadb", "mysql"},
	"sqlite":               {"sqlite"},

	// 代理/负载均衡
	"cloudflare":          {"cloudflare"},
	"akamai":              {"akamai"},
	"varnish":             {"varnish"},
	"haproxy":             {"haproxy"},
	"f5 big-ip":           {"f5", "bigip"},
	"citrix":              {"citrix"},
	"aws":                 {"aws", "amazon"},
	"amazon web services": {"aws", "amazon"},

	// 安全设备
	"fortinet":   {"fortinet", "fortigate"},
	"fortigate":  {"fortinet", "fortigate"},
	"palo alto":  {"paloalto"},
	"cisco":      {"cisco"},
	"sonicwall":  {"sonicwall"},
	"checkpoint": {"checkpoint"},
	"juniper":    {"juniper"},

	// 邮件服务器
	"microsoft exchange": {"exchange", "microsoft"},
	"exchange":           {"exchange", "microsoft"},
	"zimbra":             {"zimbra"},
	"roundcube":          {"roundcube"},
	"squirrelmail":       {"squirrelmail"},

	// 版本控制
	"gitlab":     {"gitlab"},
	"github":     {"github"},
	"bitbucket":  {"bitbucket", "atlassian"},
	"gitea":      {"gitea"},
	"gogs":       {"gogs"},
	"svn":        {"svn"},
	"subversion": {"svn"},

	// CI/CD
	"jenkins":   {"jenkins"},
	"bamboo":    {"bamboo", "atlassian"},
	"teamcity":  {"teamcity"},
	"travis ci": {"travis"},
	"circleci":  {"circleci"},
	"drone":     {"drone"},
	"argo":      {"argo"},

	// 容器/编排
	"docker":     {"docker"},
	"kubernetes": {"kubernetes", "k8s"},
	"rancher":    {"rancher"},
	"portainer":  {"portainer"},
	"openshift":  {"openshift"},

	// 监控
	"grafana":    {"grafana"},
	"prometheus": {"prometheus"},
	"zabbix":     {"zabbix"},
	"nagios":     {"nagios"},
	"kibana":     {"kibana", "elastic"},
	"splunk":     {"splunk"},
	"datadog":    {"datadog"},

	// 消息队列
	"rabbitmq": {"rabbitmq"},
	"kafka":    {"kafka"},
	"activemq": {"activemq"},
	"zeromq":   {"zeromq"},

	// 其他常见应用
	"phpmyadmin":       {"phpmyadmin"},
	"adminer":          {"adminer"},
	"phpinfo":          {"php"},
	"php":              {"php"},
	"perl":             {"perl"},
	"python":           {"python"},
	"ruby":             {"ruby"},
	"node.js":          {"nodejs"},
	"java":             {"java"},
	"go":               {"golang"},
	"solr":             {"solr", "apache"},
	"apache solr":      {"solr", "apache"},
	"lucene":           {"lucene"},
	"nexus":            {"nexus"},
	"sonatype nexus":   {"nexus"},
	"artifactory":      {"artifactory"},
	"jira":             {"jira", "atlassian"},
	"atlassian jira":   {"jira", "atlassian"},
	"servicenow":       {"servicenow"},
	"salesforce":       {"salesforce"},
	"sap":              {"sap"},
	"oracle e-business": {"oracle"},
	"peoplesoft":       {"peoplesoft", "oracle"},
	"siebel":           {"siebel", "oracle"},
	"webmin":           {"webmin"},
	"cpanel":           {"cpanel"},
	"plesk":            {"plesk"},
	"directadmin":      {"directadmin"},
	"ispconfig":        {"ispconfig"},
	"zentyal":          {"zentyal"},
	"openvpn":          {"openvpn"},
	"wireguard":        {"wireguard"},
	"keycloak":         {"keycloak"},
	"okta":             {"okta"},
	"auth0":            {"auth0"},
	"cas":              {"cas"},
	"shibboleth":       {"shibboleth"},
	"moodle":           {"moodle"},
	"canvas":           {"canvas"},
	"blackboard":       {"blackboard"},
	"odoo":             {"odoo"},
	"erpnext":          {"erpnext"},
	"suitecrm":         {"suitecrm"},
	"sugarcrm":         {"sugarcrm"},
	"vtiger":           {"vtiger"},
	"dolibarr":         {"dolibarr"},
	"mantis":           {"mantis"},
	"redmine":          {"redmine"},
	"trac":             {"trac"},
	"bugzilla":         {"bugzilla"},
	"osticket":         {"osticket"},
	"otrs":             {"otrs"},
	"glpi":             {"glpi"},
	"snipe-it":         {"snipeit"},
	"owncloud":         {"owncloud"},
	"nextcloud":        {"nextcloud"},
	"seafile":          {"seafile"},
	"pydio":            {"pydio"},
	"filerun":          {"filerun"},
	"rocketchat":       {"rocketchat"},
	"mattermost":       {"mattermost"},
	"slack":            {"slack"},
	"discord":          {"discord"},
	"matrix":           {"matrix"},
	"element":          {"element", "matrix"},
	"zulip":            {"zulip"},
	"discourse":        {"discourse"},
	"flarum":           {"flarum"},
	"phpbb":            {"phpbb"},
	"vbulletin":        {"vbulletin"},
	"xenforo":          {"xenforo"},
	"mybb":             {"mybb"},
	"smf":              {"smf"},
	"invision":         {"invision"},
	"vanilla":          {"vanilla"},
	"nodebb":           {"nodebb"},
	"humhub":           {"humhub"},
	"elgg":             {"elgg"},
	"buddypress":       {"buddypress", "wordpress"},
	"piwigo":           {"piwigo"},
	"lychee":           {"lychee"},
	"photoprism":       {"photoprism"},
	"jellyfin":         {"jellyfin"},
	"plex":             {"plex"},
	"emby":             {"emby"},
	"kodi":             {"kodi"},
	"airsonic":         {"airsonic"},
	"subsonic":         {"subsonic"},
	"ampache":          {"ampache"},
	"navidrome":        {"navidrome"},
	"home assistant":   {"homeassistant"},
	"openhab":          {"openhab"},
	"domoticz":         {"domoticz"},
	"pi-hole":          {"pihole"},
	"adguard":          {"adguard"},
	"unifi":            {"unifi", "ubiquiti"},
	"ubiquiti":         {"ubiquiti"},
	"mikrotik":         {"mikrotik"},
	"pfsense":          {"pfsense"},
	"opnsense":         {"opnsense"},
	"sophos":           {"sophos"},
	"eset":             {"eset"},
	"kaspersky":        {"kaspersky"},
	"symantec":         {"symantec"},
	"mcafee":           {"mcafee"},
	"trend micro":      {"trendmicro"},
	"bitdefender":      {"bitdefender"},
	"avast":            {"avast"},
	"avg":              {"avg"},
	"clamav":           {"clamav"},
	"comodo":           {"comodo"},
}
